name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          platforms: linux/386,linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
          push: true
          cache-from: type=registry,ref=ghcr.io/tpc3/mashiron-v:buildcache
          cache-to: type=registry,ref=ghcr.io/tpc3/mashiron-v:buildcache,mode=max
          tags: ghcr.io/tpc3/mashiron-v:latest
